export const ERROR_CODES = {
  UNAUTHORIZED: 'UNAUTHORIZED',
  FORBIDDEN: 'FORBIDDEN',
  VALIDATION_ERROR: 'VALIDATION_ERROR',
  NOT_FOUND: 'NOT_FOUND',
  PET_NOT_FOUND: 'PET_NOT_FOUND',
  USER_NOT_FOUND: 'USER_NOT_FOUND',
  APPOINTMENT_NOT_FOUND: 'APPOINTMENT_NOT_FOUND',
  INVALID_ROLE: 'INVALID_ROLE',
  FILE_TOO_LARGE: 'FILE_TOO_LARGE',
  INVALID_FILE_TYPE: 'INVALID_FILE_TYPE',
  AI_ERROR: 'AI_ERROR',
  RATE_LIMITED: 'RATE_LIMITED',
  INTERNAL_ERROR: 'INTERNAL_ERROR',
} as const;

export type ErrorCode = (typeof ERROR_CODES)[keyof typeof ERROR_CODES];

export const HTTP_STATUS: Record<ErrorCode, number> = {
  UNAUTHORIZED: 401,
  FORBIDDEN: 403,
  VALIDATION_ERROR: 400,
  NOT_FOUND: 404,
  PET_NOT_FOUND: 404,
  USER_NOT_FOUND: 404,
  APPOINTMENT_NOT_FOUND: 404,
  INVALID_ROLE: 403,
  FILE_TOO_LARGE: 400,
  INVALID_FILE_TYPE: 400,
  AI_ERROR: 503,
  RATE_LIMITED: 429,
  INTERNAL_ERROR: 500,
};
